# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806afebe33b74c090a596149f1a2b9e8ceb9278031a267e7528192c870239557df7e1112846c18b13f3c99c73da7090934e60dd0e8327b05bed7a6b012db640b

test:
  secret_key_base: 97d8b66d18507956646cea84d7d9b52b00bce9325a5ec5b4a2ee62f7900ac65155c8361f9f54f07023ee121c2b322387d3d4fc407686b4bd575fddb6b7632e8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
